title = "Bacterial population genomics"
baseURL = "https://www.bacpop.org"
languageCode = "en-gb"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "bacpop_logo.png"
  description = "Methods, software and models for analysing bacterial populations and genomes"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/bacpop"
label = "bacpop github"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/johnlees6"
label = "John's twitter"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCmp3iSn08C1wAQqC-S7evLw"
label = "ScientificProgramming YouTube channel"