title = "Pathogen Informatics and Modelling Group"
baseURL = "https://www.bacpop.org"
languageCode = "en-gb"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = "G-T91W04JTYS"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "images/bacpop_logo_3.png"
  description = "Methods, software and models for analysing bacterial populations and genomes"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  googleAnalyticsNew = "G-T91W04JTYS"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/bacpop"
label = "bacpop github"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCmp3iSn08C1wAQqC-S7evLw"
label = "ScientificProgramming YouTube channel"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
